// User
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_FAIL = "USER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// Errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Message
export const GET_MESSAGE = "GET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// Stats
export const STATS_LOADING = "STATS_LOADING";
export const STATS_LOADED = "STATS_LOADED";
export const STATS_FAIL = "STATS_FAIL";

// Student
export const STUDENT_LOADING = "STUDENT_LOADING";
export const STUDENTS_LOADED = "STUDENTS_LOADED";
export const STUDENT_LOADED = "STUDENT_LOADED";
export const STUDENT_CREATED = "STUDENT_CREATED";
export const STUDENT_UPDATED = "STUDENT_UPDATED";
export const STUDENT_DELETED = "STUDENT_DELETED";
export const STUDENT_FAIL = "STUDENT_FAIL";

// Subject
export const SUBJECT_LOADING = "SUBJECT_LOADING";
export const SUBJECTS_LOADED = "SUBJECTS_LOADED";
export const SUBJECT_LOADED = "SUBJECT_LOADED";
export const SUBJECT_CREATED = "SUBJECT_CREATED";
export const SUBJECT_UPDATED = "SUBJECT_UPDATED";
export const SUBJECT_DELETED = "SUBJECT_DELETED";
export const SUBJECT_FAIL = "SUBJECT_FAIL";

// Department
export const DEPARTMENT_LOADING = "DEPARTMENT_LOADING";
export const DEPARTMENTS_LOADED = "DEPARTMENTS_LOADED";
export const DEPARTMENT_LOADED = "DEPARTMENT_LOADED";
export const DEPARTMENT_CREATED = "DEPARTMENT_CREATED";
export const DEPARTMENT_UPDATED = "DEPARTMENT_UPDATED";
export const DEPARTMENT_DELETED = "DEPARTMENT_DELETED";
export const DEPARTMENT_FAIL = "DEPARTMENT_FAIL";
export const DEPARTMENT_SUBJECT_DELETED = "DEPARTMENT_SUBJECT_DELETED";

// Years
export const YEAR_LOADING = "YEAR_LOADING";
export const YEARS_LOADED = "YEARS_LOADED";
export const YEAR_LOADED = "YEAR_LOADED";
export const YEAR_CREATED = "YEAR_CREATED";
export const YEAR_UPDATED = "YEAR_UPDATED";
export const YEAR_DELETED = "YEAR_DELETED";
export const YEAR_FAIL = "YEAR_FAIL";

// Semester
export const SEMESTER_LOADING = "SEMESTER_LOADING";
export const SEMESTER_LOADED = "SEMESTER_LOADED";
export const SEMESTER_CREATED = "SEMESTER_CREATED";
export const SEMESTER_UPDATED = "SEMESTER_UPDATED";
export const SEMESTER_DELETED = "SEMESTER_DELETED";
export const SEMESTER_FAIL = "SEMESTER_FAIL";

// Courses
export const COURSE_LOADING = "COURSE_LOADING";
export const COURSE_LOADED = "COURSE_LOADED";
export const COURSE_CREATED = "COURSE_CREATED";
export const COURSE_UPDATED = "COURSE_UPDATED";
export const COURSE_DELETED = "COURSE_DELETED";
export const COURSE_FAIL = "COURSE_FAIL";

// Enrollments
export const ENROLLMENTS_LOADING = "ENROLLMENTS_LOADING";
export const ENROLLMENTS_LOADED = "ENROLLMENTS_LOADED";
export const ENROLLMENTS_FAIL = "ENROLLMENTS_FAIL";
export const ENROLLMENTS_CREATED = "ENROLLMENTS_CREATED";
export const ENROLLMENTS_UPDATED = "ENROLLMENTS_UPDATED";
export const ENROLLMENTS_ADD_COURSE = "ENROLLMENTS_ADD_COURSE";

//  User
export const ENROLLMENTS_STUDENT_LOADED = "ENROLLMENTS_STUDENT_LOADED";
// export const COURSE_SELECTED = "COURSE_SELECTED";
//  Admin
export const ENROLLMENTS_APPROVED = "ENROLLMENTS_APPROVED";
export const ENROLLMENT_COURSE_DELETED = "ENROLLMENT_COURSE_DELETED";
